name: tomza_kit
description: "Kit interno modular para funcionalidades reutilizables (auth, red, impresión, UI, utilidades)."

publish_to: "none"

version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  equatable: ^2.0.5
  google_fonts: ^6.3.3
  flutter_svg: ^2.2.1
  dartz: ^0.10.1
  image: ^4.5.4
  flutter_bluetooth_serial: ^0.4.0
  pdf: ^3.11.0
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  # Como librería, no requiere configuración especial aquí de assets inicialmente.
  uses-material-design: true
